/*-********************************************************************************************************
* Name         : ws_BatchToUpdateContactImage
* @Author      : Vikram Singh(vikram@wiserspread.com)
* @Date        : 17-Oct-2017
* @Description : This apex class does  
* UPDATES
* Version          Developer                    Date                        Description
*-------------------------------------------------------------------------------------------
*     1.0            vikram                       17-Oct-2017                   Initial Creation 
****************************************************************************************************************/

public with sharing class ws_BatchToUpdateContactImage{
	       
}